
# Site settings
title: Site Title
email: example@example.not
name: John Doe
#baseurl: "/subdirectory" #used if hosting in a subdirectory
url: "" # the base hostname & protocol for your site, e.g. http://example.com
blogPermalink: "/blog/" # Optional, used by post layout. If absent, "Blog"
                        # link will point to root.

# Put your logo image file in assets/logo.
# If you don't want a logo, comment the following 5 lines out.
defaults:
  - scope: # Sets the logo image to be used in the posts and post layout.
      path: "assets/logo"
    values:
      logoImage: true

# If you want to link only specific pages in your footer or home page, 
# uncomment the corresponding variable below and add the paths to the 
# pages in order as they should show up. Otherwise, page order is set
# on each page's front matter with the order variable.

#home_pages:
# - posts.md

#footer_pages:
# - simple.md

# Build settings
exclude:
  - README.md
  - LICENSE.txt
